name: actions-tanpopo
description: Bot for automation of routine tasks

inputs:
  token:
    description: GitHub App installation token
    required: true
  dry-run:
    description: Set true to dry-run
    required: true
    default: false

runs:
  using: 'node20'
  main: 'dist/index.js'
