name: actions-tanpopo-bot

on:
  pull_request:
    paths:
      - tasks/**
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/actions-tanpopo-bot.yaml
  pull_request_review_comment:
    types:
      - edited

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}--${{ github.event_name }}--${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Run int128/actions-tanpopo-bot
        uses: ./
        with:
          token: ${{ steps.token.outputs.token }}
