name: actions-tanpopo-bot

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    paths:
      - .github/workflows/actions-tanpopo-bot.yaml

jobs:
  actions-tanpopo-bot:
    if: |
      github.event_name == 'issues' && contains(github.event.issue.labels, '/tanpopo')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
      - run: npm install -g pnpm@latest-10
      - uses: int128/actions-tanpopo-bot@v0
        with:
          github-app-id: ${{ secrets.BOT_APP_ID }}
          github-app-private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          github-app-installation-id: ${{ secrets.BOT_APP_INSTALLATION_ID }}
