name: bot

on:
  pull_request:
    paths:
      - tasks/**
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/bot.yaml

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}--${{ github.event.pull_request.id }}--${{ github.actor }}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i --prod

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: int128/glob-changed-files-action@c4ff8ccd7a9ae48a4adc57a3b06a3f7ba4b22792 # v2.40.0
        id: changed-tasks
        with:
          paths: |
            tasks/:task/**
          transform: |
            :task
      - run: pnpm start
        env:
          INPUT_TASKS: ${{ steps.changed-tasks.outputs.paths }}
          INPUT_TOKEN: ${{ steps.token.outputs.token }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.BOT_GEMINI_API_KEY }}

      - if: steps.changed-tasks.outputs.paths == ''
        name: Run int128/actions-tanpopo (example)
        run: pnpm start
        env:
          INPUT_TASKS: example
          INPUT_TOKEN: ${{ steps.token.outputs.token }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.E2E_GEMINI_API_KEY }}
          
      - uses: int128/label-action@8e3c8dc3399117b88c15efdd0cc0d3177d8741a4 # v1.44.0
        id: require-smoke-test
        with:
          match-labels: |
            /require-smoke-test
      - if: steps.require-smoke-test.outputs.matched == 'true'
        name: Run int128/actions-tanpopo (smoke-test)
        run: pnpm start
        env:
          INPUT_TASKS: smoke-test
          INPUT_TOKEN: ${{ steps.token.outputs.token }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.E2E_GEMINI_API_KEY }}
